

package st.evening.kt.invokecontrol.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link st.evening.kt.invokecontrol.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("bootstrap.kt")
  public void testBootstrap() {
    runTest("compiler-plugin/testData/box/bootstrap.kt");
  }

  @Test
  @TestMetadata("bootstrapCapture.kt")
  public void testBootstrapCapture() {
    runTest("compiler-plugin/testData/box/bootstrapCapture.kt");
  }

  @Test
  @TestMetadata("closure.kt")
  public void testClosure() {
    runTest("compiler-plugin/testData/box/closure.kt");
  }

  @Test
  @TestMetadata("constructor.kt")
  public void testConstructor() {
    runTest("compiler-plugin/testData/box/constructor.kt");
  }

  @Test
  @TestMetadata("curry.kt")
  public void testCurry() {
    runTest("compiler-plugin/testData/box/curry.kt");
  }

  @Test
  @TestMetadata("delegatedConstructor.kt")
  public void testDelegatedConstructor() {
    runTest("compiler-plugin/testData/box/delegatedConstructor.kt");
  }

  @Test
  @TestMetadata("enum.kt")
  public void testEnum() {
    runTest("compiler-plugin/testData/box/enum.kt");
  }

  @Test
  @TestMetadata("explicitConstructor.kt")
  public void testExplicitConstructor() {
    runTest("compiler-plugin/testData/box/explicitConstructor.kt");
  }

  @Test
  @TestMetadata("extension.kt")
  public void testExtension() {
    runTest("compiler-plugin/testData/box/extension.kt");
  }

  @Test
  @TestMetadata("function.kt")
  public void testFunction() {
    runTest("compiler-plugin/testData/box/function.kt");
  }

  @Test
  @TestMetadata("functionRef.kt")
  public void testFunctionRef() {
    runTest("compiler-plugin/testData/box/functionRef.kt");
  }

  @Test
  @TestMetadata("generic.kt")
  public void testGeneric() {
    runTest("compiler-plugin/testData/box/generic.kt");
  }

  @Test
  @TestMetadata("inferLambda.kt")
  public void testInferLambda() {
    runTest("compiler-plugin/testData/box/inferLambda.kt");
  }

  @Test
  @TestMetadata("innerProperty.kt")
  public void testInnerProperty() {
    runTest("compiler-plugin/testData/box/innerProperty.kt");
  }

  @Test
  @TestMetadata("matching.kt")
  public void testMatching() {
    runTest("compiler-plugin/testData/box/matching.kt");
  }

  @Test
  @TestMetadata("object.kt")
  public void testObject() {
    runTest("compiler-plugin/testData/box/object.kt");
  }

  @Test
  @TestMetadata("override.kt")
  public void testOverride() {
    runTest("compiler-plugin/testData/box/override.kt");
  }

  @Test
  @TestMetadata("property.kt")
  public void testProperty() {
    runTest("compiler-plugin/testData/box/property.kt");
  }

  @Test
  @TestMetadata("propertyAccessor.kt")
  public void testPropertyAccessor() {
    runTest("compiler-plugin/testData/box/propertyAccessor.kt");
  }

  @Test
  @TestMetadata("propertyDelegate.kt")
  public void testPropertyDelegate() {
    runTest("compiler-plugin/testData/box/propertyDelegate.kt");
  }

  @Test
  @TestMetadata("readme.kt")
  public void testReadme() {
    runTest("compiler-plugin/testData/box/readme.kt");
  }

  @Test
  @TestMetadata("sam.kt")
  public void testSam() {
    runTest("compiler-plugin/testData/box/sam.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/box/simple.kt");
  }

  @Test
  @TestMetadata("var.kt")
  public void testVar() {
    runTest("compiler-plugin/testData/box/var.kt");
  }
}
