

package st.evening.kt.invokecontrol.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link st.evening.kt.invokecontrol.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class JvmDiagnosticTestGenerated extends AbstractJvmDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Test
  @TestMetadata("assignment.kt")
  public void testAssignment() {
    runTest("compiler-plugin/testData/diagnostics/assignment.kt");
  }

  @Test
  @TestMetadata("cast.kt")
  public void testCast() {
    runTest("compiler-plugin/testData/diagnostics/cast.kt");
  }

  @Test
  @TestMetadata("constructor.kt")
  public void testConstructor() {
    runTest("compiler-plugin/testData/diagnostics/constructor.kt");
  }

  @Test
  @TestMetadata("curry.kt")
  public void testCurry() {
    runTest("compiler-plugin/testData/diagnostics/curry.kt");
  }

  @Test
  @TestMetadata("delegatedConstructor.kt")
  public void testDelegatedConstructor() {
    runTest("compiler-plugin/testData/diagnostics/delegatedConstructor.kt");
  }

  @Test
  @TestMetadata("dependent.kt")
  public void testDependent() {
    runTest("compiler-plugin/testData/diagnostics/dependent.kt");
  }

  @Test
  @TestMetadata("empty.kt")
  public void testEmpty() {
    runTest("compiler-plugin/testData/diagnostics/empty.kt");
  }

  @Test
  @TestMetadata("explicitConstructor.kt")
  public void testExplicitConstructor() {
    runTest("compiler-plugin/testData/diagnostics/explicitConstructor.kt");
  }

  @Test
  @TestMetadata("expression.kt")
  public void testExpression() {
    runTest("compiler-plugin/testData/diagnostics/expression.kt");
  }

  @Test
  @TestMetadata("extend.kt")
  public void testExtend() {
    runTest("compiler-plugin/testData/diagnostics/extend.kt");
  }

  @Test
  @TestMetadata("function.kt")
  public void testFunction() {
    runTest("compiler-plugin/testData/diagnostics/function.kt");
  }

  @Test
  @TestMetadata("functionRef.kt")
  public void testFunctionRef() {
    runTest("compiler-plugin/testData/diagnostics/functionRef.kt");
  }

  @Test
  @TestMetadata("generic.kt")
  public void testGeneric() {
    runTest("compiler-plugin/testData/diagnostics/generic.kt");
  }

  @Test
  @TestMetadata("javaProperty.kt")
  public void testJavaProperty() {
    runTest("compiler-plugin/testData/diagnostics/javaProperty.kt");
  }

  @Test
  @TestMetadata("object.kt")
  public void testObject() {
    runTest("compiler-plugin/testData/diagnostics/object.kt");
  }

  @Test
  @TestMetadata("override.kt")
  public void testOverride() {
    runTest("compiler-plugin/testData/diagnostics/override.kt");
  }

  @Test
  @TestMetadata("property.kt")
  public void testProperty() {
    runTest("compiler-plugin/testData/diagnostics/property.kt");
  }

  @Test
  @TestMetadata("propertyAccessor.kt")
  public void testPropertyAccessor() {
    runTest("compiler-plugin/testData/diagnostics/propertyAccessor.kt");
  }

  @Test
  @TestMetadata("sam.kt")
  public void testSam() {
    runTest("compiler-plugin/testData/diagnostics/sam.kt");
  }

  @Test
  @TestMetadata("simple.kt")
  public void testSimple() {
    runTest("compiler-plugin/testData/diagnostics/simple.kt");
  }

  @Test
  @TestMetadata("var.kt")
  public void testVar() {
    runTest("compiler-plugin/testData/diagnostics/var.kt");
  }
}
